environment: production
database:
  host: db.internal
  password: ENC[AES-GCM,n:dc4eFnldu/VAjbky,c:nuAvmVhGbUoguvH93mp9gb1C+gU=,t:cTMIpYQviUuhmUBX2REo7w==]
api:
  token: ENC[AES-GCM,n:3XmcoOkK/euWsRkJ,c:PqJabzlqXIybCZEbDdQf,t:Q+DKv8algPjYF0PZBLeeXQ==]
cache:
  password: ENC[AES-GCM,n:+Jr/juC6QHA9rB7e,c:Elw0JVgBbULyadaHl4r0TA==,t:JD+v6ZWGY5JWCfb9/cWyww==]
kerf:
  version: 1
  cipher: aes-256-gcm
  recipients:
  - type: age
    recipient: age1aufk8k284xd903p37c9gx0g6rq5wckcecdmsxxs994qu00tphaeqjt880f
    encrypted_dek: YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOFk4M0tKajBWcFJKZ1M4SlJoeU5pR0xDOWViZzFtZ3YyZ3g1bVJzZXlBCmVHajMwdys2ODhiZUw3WHZMdXBEbkhKQ2Qvd2RzUXRickM5VmpnNEtrNG8KLT4gXk1gdF94OTwtZ3JlYXNlIEJ0TSIgfi17ZFggJGcgeT82TGAKZ3VxWVlZMUhIOXd3YXhBK2szc1U2dWFXaWcKLS0tIHRHZ2tPakxleHBNMDVMalFSRUtqQTZTTmc2NVZtUHRFOTZZOUlZUTU4MG8K9bBuTTjeX66gQATRxhixKGU45aZVJPZvwCrL+ajyseqnoeKo51FX01z1FiAdIE94aoN5aT42LUS4aykOvp+0Zw==
  encrypted_regex: ^(password|token|key|secret|credential)$
  mac: ENC[AES-GCM,n:xWxWn7Z5pxPc5dOO,c:Z1/xcmt6dDYZEQlFA9STOBjrmy1MAwiL3Sz0v/+NLtU=,t:CncRudSjUbtZ4q6ANCx8wA==]
